name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t aggregator-image -f build/Dockerfile .

#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.22
##      - name: Install Docker CLI Plugins
##        run: |
##          sudo apt-get update
##          sudo apt-get install docker-compose
#
#      - name: Build
#        run: go build -v ./...